### ISSUE TITLE
Ep 01 | Masking

### ISSUE THREAD

**Issue by josephmje** [jerdra/scwg2018_python_neuroimaging#10]
@jerdra not sure what you meant by `reshape` command here

- [ ] explain benefits of masking (operations on data are only applied within masked area, results in faster performance)

**Comment by jerdra** [comment]
ah I meant there was use of reshape like:

<code> x.reshape( (dim,-1) ) </code> 

There was no explanation for 
a. What reshape does, how does it work? It's easy to think about it in terms of changing dimension size but *how* does the actual data change? How are the rows/columns being shifted around? 
b. The use of (-1) in reshape should be explained cause its really useful

**Comment by jerdra** [comment]
ah sorry just took another look. You use -1 to refer to the last element in the array (instead of as an arg to reshape), as long as it's mentioned we should be good. But point (a) still stands.
