### ISSUE TITLE
Ep 02 | Basic Image Operations

### ISSUE THREAD

**Issue by josephmje** [jerdra/scwg2018_python_neuroimaging#13]
- [x] explain difference between `nibabel` and `nilearn` plotting (same thing)

**Comment by jerdra** [comment]
i think we can just make a note while teaching to say that it's doing the same thing as nibabel's orthosliceviewer and that both are equally valid solution to viewing images. Just so people aren't confused about nilearn's viewer being a "special case" for nilearn-type problems.

**Comment by jerdra** [comment]
closing since complete!
