### ISSUE TITLE
Download data onto SciNet and set up Jupyter notebooks

### ISSUE THREAD

**Issue by josephmje** [jerdra/scwg2018_python_neuroimaging#19]
- [x] download data onto SciNet
- [x] create simple instructions for learners to set up Jupyter notebooks and access data

**Comment by kaitj** [comment]
Were there specific nodes that learners would be using for the summer school? I have some instructions that I had previously written for setting up Jupyter to use on Graham that can likely be adapted for Niagara.

**Comment by josephmje** [comment]
COMPUTE CLUSTER

During the summer school, we will be using SciNet's Teach cluster.
This cluster consists of 42 nodes with 16 cores and 64 GB or more RAM.
You can login using:

 ssh teach.scinet.utoronto.ca

This gets you to the teach01 node, which is the login node. All
instructors should have access as of today (June 14 2019).

You can request an interactive session with the 'debugjob' command.
This command gives you access to a single core on one of the teach
nodes for three hours.  To get more than one core (useful for the
parallel programming sessions), use the "-n" option, e.g.

 debugjob -n 4

gets you 4 cores on a single node for 4 hours, and

 debugjob -n 32

gets you 2 nodes of 16 cores each, for 2 hours.

The file system of the Teach cluster is the same as that of Niagara.
A directory for teaching materials and code has been created at

 /scinet/course/ss2019

You can put material for streams 1, 2, and 3 in a
subdirectory on /scinet/course/ss2019/1, /scinet/course/ss2019/2, and
/scinet/course/ss2019/3 respectively.

For those sessions using Jupyter notebooks (many of the biomedical
sessions), we have set up JupyterHubs on 5 nodes of the Teach
cluster. You can start testing this by setting up a tunnel like this:

 ssh -L 8888:jupyterhub:8000 teach.scinet.utoronto.ca -N

and then point the browser to localhost:8888 . Your browser will
complain that the connection is insecure, ignore that.

For more information on the teach cluster see:
https://docs.scinet.utoronto.ca/index.php/Teach.

**Comment by josephmje** [comment]
I've downloaded the data into our scinet folder:
`/scinet/course/ss2019/3/6_mripython/data`

**Comment by kaitj** [comment]
To do: 
* Test data
* Try shared environment?

**Comment by kaitj** [comment]
Instructions can be found here (will change to comment only later on): https://docs.google.com/document/d/1BORB094IIb_jGliJ4BCDACqw8tSaHmrNuE38cRq89s0/edit#heading=h.ioh9yxwtwhuh 

Wasn't able to make any changes to the virtual environment so I've created a conda environment `/scinet/course/ss2019/3/6_mripython/mripython_conda` with the same module versions in the virtual environment in order to be able to add the kernel to Jupyterhub.

Tested and was able to access the data above via pybids.

**Comment by jerdra** [comment]
great thanks for doing this! I'll give it shot sometime today and let you know how it goes

**Comment by jerdra** [comment]
@kaitj getting an error saying open failed: administratively prohibited: open failed
Probably should contact Ramses about this if it's on their end?

**Comment by kaitj** [comment]
@jerdra Oh that is strange, @ostanley was going to test it out again this morning. Which step was the error happening at?

**Comment by jerdra** [comment]
after setting up the jupyterhub port and opening localhost:8888! Gonna try again on the lab computer right now!

**Comment by jerdra** [comment]
nope :cry: doesn't work here for the same reasons

**Comment by ostanley** [comment]
Yep, I get the error: channel 2: open failed: administratively prohibited: open failed when I follow the documentation as written.
It works for: ssh -L 8888:jupyterhub7:8000 ostanle2@teach.scinet.utoronto.ca -N
Could it be a permissions thing?
Maybe we need to contact Ramses about it?

**Comment by jerdra** [comment]
cool will email him!

**Comment by kaitj** [comment]
I see under "Hand-on sessions" on the website there is information about connecting to jupyterhub and it looks like it should read `ssh -L 8888:jupyterhubX:8000 <user>@teach.scinet.utoronto.ca -N", setting X to 1-7. I'll change that in the documentation.

https://support.scinet.utoronto.ca/education/go.php/441/content.php/cid/1775/

**Comment by jerdra** [comment]
yeah good catch! but doesn't work either though :(

**Comment by jerdra** [comment]
sent email!

**Comment by ostanley** [comment]
That is what worked for me just now with X=7. I had to put my username in though.

**Comment by jerdra** [comment]
<code>ssh -L 8888:jupyterhub6:8000 jerroldj@teach.scinet.utoronto.ca -N</code>

Doesn't work for me

**Comment by josephmje** [comment]
@jerdra I got it working for me but I had to change the port to 8887 instead of 8888. I think my computer already had something on 8888.

**Comment by jerdra** [comment]
Lol it magically works for me too, and so does 8888

**Comment by jerdra** [comment]
just finished creating a setup workshop script to automatically download the data and repo! Please test if you can and let me know if you run into issues. I'm gonna do a sanity check on the scripts and the Binder instance to make sure everything runs smoothly in a bit.

**Comment by jerdra** [comment]
@ostanley @josephmje @kaitj

**Comment by ostanley** [comment]
Script works! Created a folder in my home directory with all the notebooks and symlinked data. Notebook 2 runs and accesses data appropriately on jupyterhub7 instance.

I am hitting the road, see you all tomorrow!

**Comment by jerdra** [comment]
brilliant thanks for checking! See you tmrw!

**Comment by jerdra** [comment]
let's publish the instructions in the README or add them to slides at the beginning!

**Comment by kaitj** [comment]
Either one works! We can also link the doc on the Python for MRI Analysis page. 

Also wanted to note I changed the access to the doc from "edit" to "comment"
