### ISSUE TITLE
Ep 01 | Affine

### ISSUE THREAD

**Issue by josephmje** [jerdra/scwg2018_python_neuroimaging#7]
- [ ] include better explanation of affine transform
- [ ] explain reference space/world-coordinates/data space

**Comment by jerdra** [comment]
Idea for tackling this:

Show a 2D slice at some Z-coordinate. Then highlight a pixel saying in image pixels it is in location (x,y,z). Where X,Y are counted from the top left corner of the image. These are measured by "pixels/voxels" in the image. 

Then talk about "real coordinates", these are measurements in millimeters inside the scanner. We need a way of going back and forth between "pixel coordinates" and "real world scanner measurements".

Something like that maybe? I think there's diagrams of RAS in scanner cartesian grids somewhere in the interwebs

**Comment by josephmje** [comment]
Yup I think nibabel has a good image. I was also thinking that talking
about the coordinates here could help frame registration really nicely.

**Comment by jerdra** [comment]
Yup totally agree, but i don't think we're talking about registration in the course are we?
